### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by shuyu888** [ifzhang/ByteTrack#174]
Traceback (most recent call last):
  File "tools/train.py", line 112, in <module>
    assert num_gpu <= torch.cuda.device_count()
AssertionError

**Comment by Melikamuliyih** [comment]
"yolox/data/datasets/mot.py", line 102, in pull_item
    assert img is not None
AssertionError

**Comment by Dev-ori** [comment]
> Traceback (most recent call last): File "tools/train.py", line 112, in assert num_gpu <= torch.cuda.device_count() AssertionError

I've got same error when train the model followed by

**Comment by Melikamuliyih** [comment]
@shuyu888 Check your machine has GPU

**Comment by Melikamuliyih** [comment]
> 

I've had got this problem too, and I had solved by downloading pytorch with cuda version

**Comment by Dev-ori** [comment]
> > 
> 
> I've had got this problem too, and I had solved by downloading pytorch with cuda version and aslo try the with gpu device 0. instead of -d use -d 0

Thx a lot. 
I've tried following you. and I could see the "exp value" table. but still get an error as bellow. 
did this happend to you ? 
![image](https://user-images.githubusercontent.com/34330956/163766706-f612a3aa-f4b4-49eb-b1f6-46c3ee3be1cd.png)

**Comment by Melikamuliyih** [comment]
> 
Sorry, I didnt got this

**Comment by Dev-ori** [comment]
> > 
> 
> Sorry, I didnt got this

https://github.com/ifzhang/ByteTrack/issues/57

Guess this was the problem. Thx. good day :)

**Comment by Melikamuliyih** [comment]
> > > 
> > 
> > 
> > Sorry, I didnt got this
> 
> #57
> 
> Guess this was the problem. Thx. good day :)

Good

But I've got this problem

"yolox/data/datasets/mot.py", line 102, in pull_item
assert img is not None
AssertionError

**Comment by Dev-ori** [comment]
> 

As for my experience, those 'AsserstionError's occured by 'yolox' version or packages. 
So, I'd solved by deleting yolox and packages. or simply just delelting the whole 'Bytetrack' folder and re-download and re install by the following steps noted at the 'readme.md'.

I guess there could be some collision between install steps.

**Comment by TheMadScientiist** [comment]
> > > Sorry, I didnt got this
> > 
> > 
> > #57
> > Guess this was the problem. Thx. good day :)
> 
> Good
> 
> But I've got this problem
> 
> "yolox/data/datasets/mot.py", line 102, in pull_item assert img is not None AssertionError

I’ve also ran into this problem, where you able to solve it?

**Comment by TheMadScientiist** [comment]
> "yolox/data/datasets/mot.py", line 102, in pull_item
> assert img is not None
> AssertionError

I also ran into this problem, were you able to solve it?

**Comment by Melikamuliyih** [comment]
> 



> > "yolox/data/datasets/mot.py", line 102, in pull_item
> > assert img is not None
> > AssertionError
> 
> I also ran into this problem, were you able to solve it?

If you get wannings, try to solve them

**Comment by forever208** [comment]
it is generally the issue of wrong image directoies,
you can print out the dir for debugging.

**Comment by parthmalpathak** [comment]
Any other update on Solving this problem? I have tried pytorch with cuda version and it still doesn't work. Any other way round it or should I simply reinstall ByteTrack.

**Comment by parthmalpathak** [comment]
@TheMadScientiist just to confirm, the datasets folder already has 'mot' which contains MOT17- train, test and annotations. Apart from that can you tell me where to store mix_det, mix_mot_20_ch and mix_mot_ch? Because I have just kept them as directories along with ETHZ, cityscapes and other datasets
<img width="648" alt="Screen Shot 2022-06-27 at 10 29 56 AM" src="https://user-images.githubusercontent.com/65437782/176000818-2e220d30-fe79-4ab6-9ebd-f5f27a598bd2.png">

**Comment by TheMadScientiist** [comment]
In the ETHZ and cityscapes directories are there train, test, and annotations like the “mot” folder?

**Comment by parthmalpathak** [comment]
datasets
   |——————mot
   |        └——————train
   |        └——————test
   └——————crowdhuman
   |         └——————Crowdhuman_train
   |         └——————Crowdhuman_val
   |         └——————annotation_train.odgt
   |         └——————annotation_val.odgt
   └——————MOT20
   |        └——————train
   |        └——————test
   └——————Cityscapes
   |        └——————images
   |        └——————labels_with_ids
   └——————ETHZ
            └——————eth01
            └——————...
            └——————eth07


The folders are made the same way as suggested in the README. They have the same content. Each folder has annotations extra when you convert to COCO by running the .py files.

**Comment by parthmalpathak** [comment]
@TheMadScientiist can you please attach a snap of your datasets directory and let me know how have you saved the different datasets?

**Comment by 5211314whb** [comment]
> > “yolox/data/datasets/mot.py”，第 102 行，在 pull_item 中
> > 断言 img 不是 None 
> > AssertionError
> 
> 我也遇到了这个问题，请问你解决了吗？

**Comment by 5211314whb** [comment]
> “yolox/data/datasets/mot.py”，第 102 行，在 pull_item 中 断言 img 不是 None AssertionError

请问你解决了吗

**Comment by gyh420** [comment]
> > > 
> > 
> > 
> > I've had got this problem too, and I had solved by downloading pytorch with cuda version and aslo try the with gpu device 0. instead of -d use -d 0
> 
> Thx a lot. I've tried following you. and I could see the "exp value" table. ![image](https://user-images.githubusercontent.com/34330956/163766898-ba7fee95-80c9-44e5-bb03-bc88582ec1fe.png) **but** still get an error as bellow. did this happend to you ? ![image](https://user-images.githubusercontent.com/34330956/163766706-f612a3aa-f4b4-49eb-b1f6-46c3ee3be1cd.png)

l change the d to 0, but l get this problem  No such file or directory: 'pretrained/yolox_x.pth' , how to fix it

**Comment by 5211314whb** [comment]
You can create a new folder in your root directory. Name it pretrained, and put yolox_x.pth in it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ifzhang/ByteTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月29日(星期二) 晚上10:26
***@***.***&gt;;
抄送:&nbsp;"指尖@***@***.******@***.***&gt;;
主题:&nbsp;Re: [ifzhang/ByteTrack] AssertionError (Issue #174)





     
I've had got this problem too, and I had solved by downloading pytorch with cuda version and aslo try the with gpu device 0. instead of -d use -d 0
  
Thx a lot. I've tried following you. and I could see the "exp value" table.  but still get an error as bellow. did this happend to you ? 
  
l change the d to 0, but l get this problem  No such file or directory: 'pretrained/yolox_x.pth' , how to fix it

**Comment by gyh420** [comment]
> > “yolox/data/datasets/mot.py”，第 102 行，在 pull_item 中 断言 img 不是 None AssertionError
> 
> 请问你解决了吗

hi ,when i run python3 tools/convert_crowdhuman_to_coco.py, l have this question,  [Errno 2] No such file or directory: 'datasets/crowdhuman/CrowdHuman_val/273271,c9db000d5146c15.jpg', but l have cheek it, there have the 273271,c9db000d5146c15.jpg, how to fix it?

**Comment by 5211314whb** [comment]
这个没有，我也是这个错误，得问作者




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月4日(星期天) 上午9:01
收件人: ***@***.***&gt;; 
抄送: "指尖@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ifzhang/ByteTrack] AssertionError (Issue #174)





   
“yolox/data/datasets/mot.py”，第 102 行，在 pull_item 中 断言 img 不是 None AssertionError
  
请问你解决了吗
  
hi ,when i run python3 tools/convert_crowdhuman_to_coco.py, l have this question,  [Errno 2] No such file or directory: 'datasets/crowdhuman/CrowdHuman_val/273271,c9db000d5146c15.jpg', but l have cheek it, there have the 273271,c9db000d5146c15.jpg, how to fix it?

**Comment by gyh420** [comment]
> 这个没有，我也是这个错误，得问作者
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年12月4日(星期天) 上午9:01 收件人: ***@***.***&gt;; 抄送: "指尖@***@***.***&gt;; ***@***.***&gt;; 主题: Re: [ifzhang/ByteTrack] AssertionError (Issue #174) “yolox/data/datasets/mot.py”，第 102 行，在 pull_item 中 断言 img 不是 None AssertionError 请问你解决了吗 hi ,when i run python3 tools/convert_crowdhuman_to_coco.py, l have this question, [Errno 2] No such file or directory: 'datasets/crowdhuman/CrowdHuman_val/273271,c9db000d5146c15.jpg', but l have cheek it, there have the 273271,c9db000d5146c15.jpg, how to fix it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

when i run python tools/train.py -f exps/example/mot/yolox_x_ablation.py -d 8 -b 48 --fp16 -o -c pretrained/yolox_x.pth, it assert num_gpu <= torch.cuda.device_count(), any suggestion?

**Comment by gyh420** [comment]
> > “yolox/data/datasets/mot.py”，第 102 行，在 pull_item 中 断言 img 不是 None AssertionError
> 
> 请问你解决了吗

now, l get the same question,how you fix it ?

**Comment by 5211314whb** [comment]
I also have the same problem, which has not been solved. Is there a bug in the original code?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ifzhang/ByteTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月4日(星期天) 下午3:36
***@***.***&gt;;
抄送:&nbsp;"指尖@***@***.******@***.***&gt;;
主题:&nbsp;Re: [ifzhang/ByteTrack] AssertionError (Issue #174)





      
Sorry, I didnt got this
  
#57
 Guess this was the problem. Thx. good day :)
  
Good
 
But I've got this problem
 
"yolox/data/datasets/mot.py", line 102, in pull_item assert img is not None AssertionError
  
l have the same question, how you fix it ?

**Comment by gyh420** [comment]
> assert img is not None

assert img is not None   how you fix it?

**Comment by gyh420** [comment]
> > “yolox/data/datasets/mot.py”，第 102 行，在 pull_item 中 断言 img 不是 None AssertionError
> 
> 请问你解决了吗

any result?  l have  assert img is not None too

**Comment by silverAugustine** [comment]
maybe you can change the command line 
(e.g. from "python train_net.py --num-gpus 8(this num is too big) " to "python train_net.py --num-gpus 2(the number is up to your num of gpus, I recommand you to rise it from 1)")
